version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - '/tmp/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  aws-cli:
    image: mesosphere/aws-cli
    environment:
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=sa-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 10
        aws sqs create-queue --endpoint-url=http://localstack:4566 --queue-name producer-orders
        sleep 5
        echo Listing queues
        aws sqs --endpoint-url http://localstack:4566 list-queues
      
        while true; do aws sqs --endpoint-url http://localstack:4566 send-message --queue-url http://localhost:4566/000000000000/producer-orders --message-body "15"; sleep 90; done
        sleep 5
      
      "
    depends_on:
      - localstack